#ifndef MACROS_INC		//Header sentry
#define MACROS_INC

/* ************************************** MACROS ***************************** */

/*
#define MAC_MIDI_In_Inc_Index(index, max_index) { 	index++; \
    							if(index >= max_index)  \
       							   index = 0; }

#define MAC_MIDI_In_Add_Index(index, added, max_index) { index = index+added; \
    							if(index >= max_index)  \
       							   index -= max_index; }
*/

#endif

