INCLUDE "..\..\common_z8_ez\identity_inc.asm"
;INCLUDE "..\..\common_z8_ez\common_z8_ez.h"

;define IDENTITY_ADDRESS, org=0E00H
;segment IDENTITY_ADDRESS
;globals ON
;xref FW_VERSION:public
;.extern FW_VERSION,FW_SUB_VERSION,HW_VERSION,HW_SUB_VERSION,MANUF_YEAR,MANUF_MONTH,SERIAL_4,SERIAL_3,SERIAL_2,SERIAL_1,SERIAL_0
;_identity db FW_VERSION,FW_SUB_VERSION,HW_VERSION,HW_SUB_VERSION,MANUF_YEAR,MANUF_MONTH,SERIAL_4,SERIAL_3,SERIAL_2,SERIAL_1,SERIAL_0

define 	IDENTITY_ADDRESS, space=rom
segment IDENTITY_ADDRESS
ORG    	%0E00
;.extern FW_VERSION,FW_SUB_VERSION,HW_VERSION,HW_SUB_VERSION,MANUF_YEAR,MANUF_MONTH,SERIAL_4,SERIAL_3,SERIAL_2,SERIAL_1,SERIAL_0
.def 	_identity
_identity:
		db	FW_VERSION,FW_SUB_VERSION,HW_VERSION,HW_SUB_VERSION,MANUF_YEAR,MANUF_MONTH,SERIAL_4,SERIAL_3,SERIAL_2,SERIAL_1,SERIAL_0

 

 			
